# The port number for the proxy service. The proxied OpenAI API endpoint will be: http://localhost:3700/v1/chat/completions
port = 3701

# A list of poe tokens. You can get them from the cookies on poe.com, they look like this: p-b=fdasac5a1dfa6%3D%3D
tokens = ["fdasac5a1dfa6%3D%3D"]

# The proxy that will be used to connect to poe.com. Leave it blank if you do not use a proxy
proxy = ""

# Use leading prompts to indicate roles if enabled. You'd better disable it if you are using tools like https://github.com/TheR1D/shell_gpt
# 0:disable, 1:enable, 2:auto detect
# Example:
# ||>User:
# Hello!
# ||Assistant:
# Hello! How can I assist you today?
simulate-roles = 2

# Rate limit. Default to 10 api calls per token in 1 minute
rate-limit = 10

# Cool down of seconds. One same token cannot be used more than once in n seconds
cool-down = 3

# Auto reload client of minutes.
auto-reload = 10

# Timeout of seconds per response chunk
# This timeout will now reset every time a chunk is received
# so there's no need for a very large value to compensate for a very long reply
timeout = 15
# Timeout for poe-api, usually it should be smaller than timeout
api-timeout = 12


# The bot name map to use from poe.
[bot]
	"gpt-3.5-turbo" = "ChatGPT" # ChatGPT 3.5
	"gpt-3.5-turbo-0301" = "ChatGPT" # Claude-instant
	"gpt-4" = "GPT-4" # ChatGPT 4
	"gpt-4-0314" = "GPT-4" #
	"gpt-4-32k" = "GPT-4-32k" #
	"claude-2-100k" = "Claude-2-100k" # Claude-2-100k